### ISSUE TITLE
Project still maintained?

### ISSUE THREAD

**Issue by rngtng** [yoshum/issue-to-jekyll-post#19]
Hey @yoshum is this project still maintained? I've some idea, features in mind, what's you preferred way to contribute?

**Comment by yoshum** [comment]
Thanks for your interest in this project!
But no, it's not maintained now. I'll be happy to point to your fork in README if you have some updates.

**Comment by rngtng** [comment]
ok thanks your response. I'll work on my fork then and let you know once it's ready.. Thanks again for your great initial work, saved me already some time & coding!
